// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolutionMapAPI.Data;

namespace PolutionMapAPI.Migrations
{
    [DbContext(typeof(MeasurementContext))]
    [Migration("20210625140358_InitilMigatio")]
    partial class InitilMigatio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PolutionMapAPI.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("PolutionMapAPI.Models.MeasurementProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("MeasurementId")
                        .HasColumnType("integer");

                    b.Property<int>("Noise")
                        .HasColumnType("integer");

                    b.Property<int>("Polution")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementId")
                        .IsUnique();

                    b.ToTable("MeasurementProperties");
                });

            modelBuilder.Entity("PolutionMapAPI.Models.MeasurementProperties", b =>
                {
                    b.HasOne("PolutionMapAPI.Models.Measurement", null)
                        .WithOne("Properties")
                        .HasForeignKey("PolutionMapAPI.Models.MeasurementProperties", "MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolutionMapAPI.Models.Measurement", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
